// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalAluno.Infrastructure.Persistence;

#nullable disable

namespace PortalAluno.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("PortalAluno.Domain.Entities.Student", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<string>("Instrument").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<decimal?>("MonthlyPrice").HasColumnType("numeric(10,2)");
            b.Property<int?>("MonthlySessions").HasColumnType("integer");
            b.Property<DateTime?>("NextLessonAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<Guid?>("PlanId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("PlanId");
            b.ToTable("students", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Plan", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<string>("Code").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<int>("DisplayOrder").HasColumnType("integer");
            b.Property<int>("DurationMinutes").HasColumnType("integer");
            b.Property<string>("Features").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<decimal>("Price").HasColumnType("numeric(10,2)");
            b.Property<int>("SessionsPerMonth").HasColumnType("integer");
            b.Property<string>("Summary").IsRequired().HasMaxLength(400).HasColumnType("character varying(400)");

            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("plans", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Lesson", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("DurationMinutes").HasColumnType("integer");
            b.Property<string>("Justification").HasMaxLength(1000).HasColumnType("character varying(1000)");
            b.Property<DateTime?>("ResolvedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("ScheduledAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("StudentId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("ScheduledAt");
            b.HasIndex("StudentId", "Status");
            b.ToTable("lessons", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Admin", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<string>("Email").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(400).HasColumnType("character varying(400)");

            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("admins", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Repertoire", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<string>("Composer").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("StudentId").HasColumnType("uuid");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("VideoUrl").HasMaxLength(1000).HasColumnType("character varying(1000)");

            b.HasKey("Id");
            b.HasIndex("StudentId");
            b.ToTable("repertoires", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Material", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("ExternalUrl").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
            b.Property<Guid>("StudentId").HasColumnType("uuid");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");

            b.HasKey("Id");
            b.HasIndex("StudentId");
            b.ToTable("materials", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.PracticeSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<int>("Bpm").HasColumnType("integer");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<Guid>("StudentId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("StudentId", "Date");
            b.ToTable("practice_sessions", (string)null);
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Repertoire", b =>
        {
            b.HasOne("PortalAluno.Domain.Entities.Student", null)
                .WithMany("Repertoires")
                .HasForeignKey("StudentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.PracticeSession", b =>
        {
            b.HasOne("PortalAluno.Domain.Entities.Student", null)
                .WithMany("PracticeSessions")
                .HasForeignKey("StudentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Material", b =>
        {
            b.HasOne("PortalAluno.Domain.Entities.Student", null)
                .WithMany("Materials")
                .HasForeignKey("StudentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Lesson", b =>
        {
            b.HasOne("PortalAluno.Domain.Entities.Student", null)
                .WithMany()
                .HasForeignKey("StudentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Student", b =>
        {
            b.HasOne("PortalAluno.Domain.Entities.Plan", "Plan")
                .WithMany()
                .HasForeignKey("PlanId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Plan");
        });

        modelBuilder.Entity("PortalAluno.Domain.Entities.Student", b =>
        {
            b.Navigation("Materials");
            b.Navigation("PracticeSessions");
            b.Navigation("Repertoires");
        });
    }
}
